In [1]:
import numpy as np 

In [16]:
#What are we designing is 3 neurons and  4 features to make the loss = 1
np.random.seed(0) # random seed 
x = np.array([3 , -4 , 2 , 1]) # 4 feature , 1 sample
y = np.array([5]) # target to be achieved
w = np.random.randn(x.shape[0] , 3 )  # initializing weights
b = np.zeros(3) # no. of biases 
w

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351]])

In [17]:
def neurons(x , w , b):
    y_pred = np.dot(x , w) + b 
    return y_pred
def relu(y_pred):
    return np.maximum(0 , y_pred)
def total(y_pred):
    return np.sum(y_pred)
def loss(y , y_pred):
    return (y-y_pred)**2
def dl_dw_db(x , y , y_pred):
    dl_dw = 2*(y_pred - y)*x
    dl_db = 2*(y_pred - y)
    dl_dw = np.expand_dims(dl_dw , axis= 1)
    return dl_dw , dl_db
def d_relu(y_pred):
    if y_pred > 0 :
        return 1 
    else:
        return 0

In [18]:
lr = 0.001
loss_min = 9999
for i in range(10000):
    y_pred = neurons(x , w , b)
    y_pred = relu(y_pred)
    y_pred = total(y_pred)
    loss_r  = loss(y , y_pred)
    dl_dw , dl_db = dl_dw_db(x , y , y_pred)
    w = w - lr*(dl_dw*d_relu(y_pred))
    b = b - lr*(dl_db*d_relu(y_pred))

    if loss_min > loss_r :
        loss_min = loss_r
        w_opt = w 
        b_opt = b 
        print(f"Iteration : {i}  loss : {loss_min}")

Iteration : 0  loss : [9.56764667]
Iteration : 1  loss : [8.41803652]
Iteration : 2  loss : [7.40655892]
Iteration : 3  loss : [6.51661643]
Iteration : 4  loss : [5.73360587]
Iteration : 5  loss : [5.04467872]
Iteration : 6  loss : [4.4385303]
Iteration : 7  loss : [3.90521426]
Iteration : 8  loss : [3.43597933]
Iteration : 9  loss : [3.0231258]
Iteration : 10  loss : [2.6598791]
Iteration : 11  loss : [2.34027866]
Iteration : 12  loss : [2.05908014]
Iteration : 13  loss : [1.81166931]
Iteration : 14  loss : [1.59398637]
Iteration : 15  loss : [1.40245934]
Iteration : 16  loss : [1.23394544]
Iteration : 17  loss : [1.08567949]
Iteration : 18  loss : [0.95522859]
Iteration : 19  loss : [0.84045214]
Iteration : 20  loss : [0.73946677]
Iteration : 21  loss : [0.6506154]
Iteration : 22  loss : [0.57244006]
Iteration : 23  loss : [0.50365795]
Iteration : 24  loss : [0.44314043]
Iteration : 25  loss : [0.38989445]
Iteration : 26  loss : [0.34304629]
Iteration : 27  loss : [0.30182722]
Iterat

In [21]:
w_opt , b_opt

(array([[ 1.46471416,  0.10081902,  0.6793998 ],
        [ 2.64001078,  2.26667557, -0.5781603 ],
        [ 0.75052963, -0.350916  , -0.30277764],
        [ 0.31081911,  0.04426418,  1.35449411]]),
 array([-0.0997794, -0.0997794, -0.0997794]))

In [20]:

y = neurons(x , w_opt  , b_opt)
relu(y_pred)

np.float64(5.000000000000003)