In [1]:
import numpy as np

In [30]:
np.random.seed(0)
x = np.array([2 ,3])
y = np.array([1])
w = np.random.randn(x.shape[0])
b= np.zeros(1)

In [31]:
def neuron(x , w , b):
    return np.dot(x ,w.T) + b
y_pred = neuron(x , w , b)
y_pred

array([4.72857632])

In [32]:
def relu(y):
    return np.maximum(0 , y)
y_pred = relu(y_pred)
y_pred

array([4.72857632])

In [33]:
def loss(y_pred , y):
    return (y_pred - y)**2 # can also have mean and all shit but only one neuron hai :)
loss_r = loss(y_pred , y)
loss_r

array([13.90228135])

In [34]:
# now wht we need to do is reduce this loss :)
lr = 0.001
iteration = 1000
def d_relu(x) :
    if x > 0 :
        return 1 
    else:
        return 0
# weights and biases toh wrt ho rahe hai i guesss so no issue i guess
def  dl_dw_db(x , y , y_pred):
    dl_dw =  2*(y_pred  - y )*x
    dl_db = 2*(y_pred  - y )
    return dl_dw , dl_db
dl_dw , dl_db = dl_dw_db(x , y ,y_pred)

##### Penchoo saare functions ready hai bus updating and printing saving ka cheez design karna hai 

In [35]:
loss_min = 9999 # initial value 
for i in range(100000):
    loss_r = loss(y_pred , y)
    w = w - lr*dl_dw*d_relu(y_pred)
    b = b - lr*dl_db*d_relu(y_pred)
    y_pred = neuron(x , w , b)
    dl_dw , dl_db = dl_dw_db(x , y ,y_pred)

    if loss_min > loss_r :
        loss_min = loss_r
        print(loss_min , "  iteration  :" , i  )
        opt_w = w 
        opt_b = b


[13.90228135]   iteration  : 0
[13.13465298]   iteration  : 1
[12.40940999]   iteration  : 2
[11.724212]   iteration  : 3
[11.07684791]   iteration  : 4
[10.46522868]   iteration  : 5
[9.88738061]   iteration  : 6
[9.341439]   iteration  : 7
[8.82564211]   iteration  : 8
[8.33832545]   iteration  : 9
[7.87791648]   iteration  : 10
[7.44292944]   iteration  : 11
[7.03196065]   iteration  : 12
[6.64368391]   iteration  : 13
[6.27684626]   iteration  : 14
[5.93026391]   iteration  : 15
[5.60281846]   iteration  : 16
[5.29345324]   iteration  : 17
[5.00116992]   iteration  : 18
[4.72502533]   iteration  : 19
[4.46412833]   iteration  : 20
[4.21763702]   iteration  : 21
[3.98475597]   iteration  : 22
[3.76473369]   iteration  : 23
[3.55686015]   iteration  : 24
[3.36046456]   iteration  : 25
[3.17491315]   iteration  : 26
[2.99960715]   iteration  : 27
[2.83398084]   iteration  : 28
[2.67749975]   iteration  : 29
[2.52965893]   iteration  : 30
[2.38998128]   iteration  : 31
[2.25801607]   i

In [36]:
opt_w ,  opt_b 

(array([ 1.23139859, -0.39882343]), array([-0.26632688]))

In [37]:
y = neuron(x , opt_w ,  opt_b )
y

array([1.])