In [2]:
import numpy as np
import pandas as pd

Coding a single neuron which is basically a linear regresssion having Weinghts and biases   
Also it only has  one neuron without activation funtion   

In [3]:
inp = np.array([1.0 , 2.0 , 3.0 , 2.5 ])
w = np.array([0.2 , 0.8 , 0.5 , 1.0])
b = 2.0

In [4]:
#neuron
n = 0 
for i in range(w.shape[0]): #w.shape[0] defines the no. of rows
    n += inp[i]*w[i] 
n+=b 
n

np.float64(7.8)

In [5]:
n = np.dot(inp, w) + b
n

np.float64(7.8)

In [6]:
#for a layer with three neuron 
x = np.array([[1.2, 0.5, -0.7, 3.4, 2.1]])
W = np.array([[ 0.2, -0.5,  1. ],
       [ 0.7,  0.3, -1.2],
       [-0.6,  0.8,  0.4],
       [ 1.5, -0.4,  2.3],
       [ 0.9,  1.1, -0.7]
])
b = np.array([0.5, -0.2, 1.0])
W  = W.T
W

array([[ 0.2,  0.7, -0.6,  1.5,  0.9],
       [-0.5,  0.3,  0.8, -0.4,  1.1],
       [ 1. , -1.2,  0.4,  2.3, -0.7]])

In [7]:
f = np.dot(x , W) + b
f

ValueError: shapes (1,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

 Neurons  hai isiliye weights itne  hai like for each feature there is a wieght and for each neuron there are  feature with  different weights   
 So in the above case there are 5 features and 3 neurons hence the no. of weights and bias are 15 and 3 respectively   
 also the no. of rows represent no. of samples or batches which in this case is just one   
 

In [26]:
#for passing a neuron from one neuron to another 
x= np.array([[1.2, 0.5, -0.7, 3.4, 2.1
             ]]) # 5 features passed through first neuron
w1 = np.array([[ 0.2,  0.7, -0.6,  1.5,  0.9], # weights of 3 neurons in five features  1st layer
       [-0.5,  0.3,  0.8, -0.4,  1.1], 
       [ 1. , -1.2,  0.4,  2.3, -0.7]]) 
b1 = np.array([0.5, -0.2, 1.0]) # biases for three neurons of 1st layer 

w2 = np.array([[0.1, -0.14, 0.5],  #Weights of threee freatures and there neurons 
        [-0.5, 0.12, -0.33],
        [-0.44, 0.73, -0.13]])
b2 = np.array([2, 3, 0.5]) 

In [27]:
n1 = np.dot(x , w1.T) + b1

In [28]:
n2 = np.dot(n1 , w2) + b2 

In [29]:
w3 = np.array([5 , 3 , 1 ])  # one neuron in the third layer 
b3 = np.array([1])  

In [30]:
n3 = n2 @ w3.T + b3
n3

array([24.9984])

In [31]:
class blue:
    def __init__(self , nig : str): # slef its like constructor in java 
        self.name = nig  # its like the global variable :) so basic shit that i understood now
    def methods(self  , isit  : bool): 
        if isit == True :
            print("Suhail is a nigga")
        else :
            print("Still suhail is a nigga")
    def __add__(self , other) :
        name = other.name
        print(self.name , name)
    def __str__(self) -> str:
        return "Nigga"
    def __repr__(self) -> str :
        return "Representation"
hey = blue("Suhail")
noo = blue("nigga") # agr self nhi diya toh khud se variable define karna padega penchoo
(hey + noo)
print(hey )
print(repr(hey))

Suhail nigga
Nigga
Representation


In [32]:
softmax_output = np.array([0.1 ,0.1 , 0.8]) # bro its the probability of one neuron with three distinct probability of happenning  also its for one batch 
# categorical cross entropy loss 
# we labeled them as one  cross entropy  also it avg across samples and not neurons 
#assuming its one hot encoded wht we can do is 
cross_entropy = - np.log(np.max(softmax_output))
cross_entropy.tolist() 

0.2231435513142097

In [80]:
#in the case of having value less than 0.33 actualllly show that the hoghest propability is not selected having loss greter than 1 
softmax_output = np.array([[0.1 ,0.1 , 0.8],
                         [1 , 0 , 0] ,
                          [0.1 , 0.5 , 0.4]])
class_targets = [2 , 0 , 1 ]
output = softmax_output[np.arange(softmax_output.shape[0]) , class_targets]
output

array([0.8, 1. , 0.5])

In [81]:
np.max(softmax_output , axis = 1 ) # lol got the same output in both but the issue is that the above one is genuine bcz of the class target sample 

array([0.8, 1. , 0.5])

In [82]:
# now we need to claculate the cross entropy for all three as well as take the avg :)
cross_entropy = -np.log(output)
cross_entropy = np.mean(cross_entropy)
cross_entropy.tolist()

0.3054302439580517

In [89]:
# another method without labeling them as 0,1 and 2 is 
#  = [2 , 0 , 1 ] this can be one hot encodeded  as 
y_target = np.array([[0 , 0 ,1] ,
                   [1 , 0 , 0 ],
                   [0 , 1 , 0 ]])
softmax_output = np.array([[0.1 ,0.1 , 0.8],
                         [1 , 0 , 0] ,
                          [0.1 , 0.5 , 0.4]])
softmax_output = np.clip(softmax_output , 1e-7 , 1- 1e-7 ) # ayoooo les gooooooo
# actually we perform element wise multiplication thuss 
output = np.sum(y_target*softmax_output  , axis = 1 )
output

array([0.8      , 0.9999999, 0.5      ])

In [86]:
cross_entropy = -np.log(output)
cross_entropy = np.mean(cross_entropy)
cross_entropy.tolist()  # see same as that shit mannnnnnnnn crazyy

0.3054302439580517

In [ ]:
#also we clip them to close to zero and close to one bcz exacts of them will lead log to infinity or gradient calculation will be fucked up 
# so the clipping is done using np.clip and  its done btw 10^-7 and 1- 10^-7 to avoid exact values :)
